<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="A simple blog with markdown.">
    <meta name="author" content="Nodistract">

    <title>Nodistract</title>

    <!-- Highlight.js CSS -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/styles/default.min.css">

    <!-- Bootstrap core CSS -->
    <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.min.css" rel="stylesheet">

    <!-- Highlight.js -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>

    <!-- Design CSS -->
    <link href="./admin/css/blog.css" rel="stylesheet">
</head>
<body>
<div class="blog-masthead">
    <div class="container">
        <nav class="blog-nav">
            <a class="blog-nav-item active" href="#">Home</a>
            <a class="blog-nav-item" href="./admin/index.html">Admin</a>
            <a class="blog-nav-item" target="_blank" href="https://github.com/cansik/nodistract">Github</a>
        </nav>
    </div>
</div>

<div class="container">

    <header>
        <div class="blog-header">
            <h1 class="blog-title">Nodistract</h1>
            <p class="lead blog-description">A simple blog with markdown.</p>
        </div>
    </header>

    <div class="row">

        <div class="col-sm-12 blog-main">

            <?php if (isset($posts)) : ?>
                <?php foreach ($posts as $post): ?>
                    <article>
                        <div class="blog-post">
                            <a href="post/<?= htmlspecialchars($post['path']); ?>"><h2
                                    class="blog-post-title"><?= htmlspecialchars($post['title']); ?></h2></a>
                            <p class="blog-post-meta"><?= htmlspecialchars($post['publish_date']->format('F d, Y')); ?></p>
                            <div>
                                <?php
                                $Parsedown = new Parsedown();
                                echo($Parsedown->text($post['content']));
                                ?>
                            </div>
                        </div>
                    </article>
                <?php endforeach; ?>
            <?php else: ?>
                <p>Sorry, no posts found!</p>
            <?php endif; ?>


        </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
        <p>Nodistract 2016</p>
        <p>
            <a href="#">Back to top</a>
        </p>
    </footer>

    <!-- javascript -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
</body>
</html>