<html>
    <head>
        <meta charset="utf-8"/>
        <title>Nodistract</title>

        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/styles/default.min.css">
        <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/highlight.min.js"></script>
        <script>hljs.initHighlightingOnLoad();</script>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }

            a:link {
                text-decoration: none;
            }

            a:visited {
                text-decoration: none;
            }

            a:hover {
                text-decoration: underline;
            }

            a:active {
                text-decoration: underline;
            }
        </style>
    </head>
    <body>
        <a href="/"><h1>Nodistract</h1></a>
        <div>A simple blog with markdown.</div>

        <?php if (isset($posts)) : ?>
            <?php foreach($posts as $post): ?>
                <a href="post/<?= htmlspecialchars($post['path']); ?>"><h2><?= htmlspecialchars($post['title']); ?></h2></a>
                <div>
                <?php
                    $Parsedown = new Parsedown();
                    echo($Parsedown->text($post['content']));
                ?>
                </div>
            <?php endforeach; ?>
        <?php else: ?>
            <p>Sorry, no posts found!</p>
        <?php endif; ?>
    </body>
</html>
